-- Create a specific type for sports to ensure data consistency
create type public.sport_category as enum (
  'Running',
  'Cycling',
  'Multi-sport',
  'Swimming',
  'Motor',
  'Other'
);

-- PROFILES TABLE
-- Linked to Supabase Auth
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Profiles Policies
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- PARTICIPATIONS TABLE
create table public.participations (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  sport public.sport_category not null,
  year int not null,
  finish_time interval not null,
  race_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Optional: Ensure logical years (e.g., not in the distant future or past)
  constraint valid_year check (year > 1900 and year <= extract(year from now()) + 1)
);

-- Enable RLS on participations
alter table public.participations enable row level security;

-- Participations Policies
create policy "Participations are viewable by everyone."
  on public.participations for select
  using ( true );

create policy "Users can insert their own participations."
  on public.participations for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own participations."
  on public.participations for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own participations."
  on public.participations for delete
  using ( auth.uid() = user_id );

-- Helper function to handle new user creation (optional but recommended for syncing auth and profiles)
-- This requires a trigger in the Supabase dashboard or SQL editor
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username)
  values (new.id, new.raw_user_meta_data->>'username');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user creation
-- create trigger on_auth_user_created
--   after insert on auth.users
--   for each row execute procedure public.handle_new_user();
